// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2P9Fkbi7zVGFfaesjgEDVlvIysMTEVc',
    appId: '1:348865472266:web:76e24d9c92573e93447cf3',
    messagingSenderId: '348865472266',
    projectId: 'todo-app-e11e4',
    authDomain: 'todo-app-e11e4.firebaseapp.com',
    storageBucket: 'todo-app-e11e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUBeCfhHpDnIHghvE5LBiP5Zge60Q_otk',
    appId: '1:348865472266:android:13837f39ed76d30c447cf3',
    messagingSenderId: '348865472266',
    projectId: 'todo-app-e11e4',
    storageBucket: 'todo-app-e11e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7n44QJR_dhWpKnKZF5hGrKtANdAHS5o',
    appId: '1:348865472266:ios:62fc09968d4ef99e447cf3',
    messagingSenderId: '348865472266',
    projectId: 'todo-app-e11e4',
    storageBucket: 'todo-app-e11e4.appspot.com',
    iosBundleId: 'com.rahamat.todoAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7n44QJR_dhWpKnKZF5hGrKtANdAHS5o',
    appId: '1:348865472266:ios:9ab96456411e158c447cf3',
    messagingSenderId: '348865472266',
    projectId: 'todo-app-e11e4',
    storageBucket: 'todo-app-e11e4.appspot.com',
    iosBundleId: 'com.rahamat.todoAppp.RunnerTests',
  );
}
